### ISSUE TITLE
Realloc

### ISSUE THREAD

**Issue by deadshotsb** [Snowden1738/vector#1]
reallaoc() may cause a problem.

**Comment by Snowden1738** [comment]
Doesn't sound much problematic. Why don't you try a large scale allocation / deallocation using reserve and resize and see if any problem occurs?

**Comment by deadshotsb** [comment]
What if there is space in memory but the realloc fails (in case when I cannot extend due to presence of some data)

**Comment by Snowden1738** [comment]
@deadshotsb realloc never works like that. It'll look for a location which can accommodate atleast the given amount of size in a contiguous distribution and will shift the array elements to the new position and return the new base pointer. In case this never occurs, realloc will return a NULL and we can't extend memory further.
